#Azure pipeline sample

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'BuildJob'
    steps:
    - script: echo 'from build'
  - job: TestJob
    displayName: 'Test Job'
    steps:
    - script: echo 'from test'
- stage: Deploy
  displayName: 'Deplay App'
  jobs:
  - job: Publish
    displayName: 'Publish App'
    steps:
      - script: echo 'publish app'
  - job: CreateArtifact
    displayName: 'Create artifact'
    steps:
      - script: echo 'create artifact'
