#Azure pipeline sample

trigger 
- main

pool
- vmImage: 'unbuntu-lastest'

stages
- stage: Build
  displaynNme: 'Build Stage'
  jobs
  - job: BuildJob
    displayName: 'BuildJob'
    script: echo 'test'