#Azure pipeline sample

trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'BuildJob'
    steps:
     - task: DotNetCoreCLI@2
       inputs:
         command: 'restore'
         feedsToUse: 'select'
     - task: DotNetCoreCLI@2
       inputs:
         command: 'build'

     - task: DotNetCoreCLI@2
       inputs:
         command: 'publish'
         publishWebProjects: true